export default [
  // { code: '0', name: '激活' },
  { code: '25', name: '关键行为' },
  { code: '1', name: '注册' },
  { code: '2', name: '付费' },
  { code: '3', name: '表单' },
  { code: '4', name: '在线咨询' },
  { code: '5', name: '有效咨询' },
  // { code: '6', name: '次留' },
  { code: '20', name: 'app内下单' },
  { code: '21', name: 'app内访问' },
  { code: '22', name: 'app内添加购物车' },
  { code: '23', name: 'app内付费' },
  { code: '28', name: '授权' },
  { code: '29', name: 'app内详情页到站uv' },
  { code: '179', name: '点击商品' },
  { code: '128', name: '加入收藏/心愿单' },
  { code: '213', name: '领取优惠券' },
  { code: '175', name: '立即购买' },
  { code: '212', name: '添加/选定收货信息、电话' },
  { code: '127', name: '添加/选定支付信息，绑定支付宝、微信、银行卡等' },
  { code: '176', name: '提交订单' },
  { code: '214', name: '订单提交/确认收货' },
  { code: '202', name: '进入直播间' },
  { code: '204', name: '直播间内点击关注按钮' },
  { code: '205', name: '直播间内评论' },
  { code: '206', name: '直播间内打赏' },
  { code: '207', name: '直播间内点击购物车按钮' },
  { code: '208', name: '直播间内商品点击' },
  { code: '209', name: '直播间进入种草页跳转到第三方' },
  { code: '210', name: '直播-加购' },
  { code: '211', name: '直播-下单' }
]
