export default [
  // { code: '1', name: '激活' },
  { code: 'ctivate', name: '激活', desc: '用户首次打开app' },
  { code: 'register', name: '注册', desc: '用户产生注册行为' },
  { code: 'retain', name: '次留', desc: '用户激活后次日内打开app' },
  { code: 'paid', name: '付费', desc: '用户产生付费行为' },
  { code: 'browse', name: '浏览', desc: '用户产生浏览行为' },
  { code: 'collection', name: '收藏', desc: '用户产生收藏行为' },
  { code: 'preOrder', name: '下单', desc: '用户产生下单行为' },
  { code: 'subscribe', name: '订阅', desc: '用户完成某项服务/频道订阅行为' },
  { code: 'login', name: '登陆', desc: '用户完成登陆行为' },
  { code: 'update', name: '更新', desc: '用于追踪更新事件' },
  { code: 'reservation', name: '预约服务', desc: '用户预约了某项服务' },
  { code: 'addToCart', name: '加入购物车', desc: '用户产生加入购物车行为' },
  { code: 'threeDayRetain', name: '3日留存用户在激活后', desc: '3天内打开APP' },
  { code: 'sevenDayRetain', name: '7日留存用户在激活后', desc: '7天内打开APP' },
  { code: 'deliver', name: '订单发货', desc: '用户产生下单行为后发货' },
  { code: 'orderSigning', name: '订单签收', desc: '用户产生下单行为后签收' },
  { code: 'firstPurchase', name: '首次购买', desc: '首次购买' },
  { code: 'purchaseMemberCard', name: '购买会员', desc: '购买会员' },
  {
    code: 'addQuickApp',
    name: '快应用添加',
    desc: '用户通过广告打开快应用，并将快应用添加到桌面的行为'
  },
  { code: 'addToWishlist', name: '添加到心愿清单', desc: '用户添加产品或服务到心愿清单' },
  {
    code: 'openedFromPushNotification',
    name: '从推送通知打开',
    desc: '用于追踪从推送通知打开应用的事件'
  },
  { code: 'reEngage', name: '用户唤醒', desc: '打开app' },
  { code: 'keyAction', name: '关键行为', desc: '用户关键行为' },
  { code: 'form_submit', name: '表单提交', desc: '用于追踪表单提交行为' },
  { code: 'consult', name: '有效咨询', desc: '获取有效咨询' },
  {
    code: 'effectiveLeadsForm',
    name: '有效线索-表单',
    desc: '广告主投放的表单线索回拨后确认为有效线索'
  },
  {
    code: 'potentialCustomerForm',
    name: '潜在客户线索-表单',
    desc: '广告主投放的表单线索回拨后确认为潜在客户'
  },
  { code: 'custom_acquisit', name: '有效获客', desc: '获取有效客户' },
  { code: 'book', name: '有效预定', desc: '获取有效预定' },
  { code: 'consultOnline', name: '网页咨询', desc: '用户在网页进行咨询操作' },
  {
    code: 'effectiveLeadsOnline',
    name: '有效线索-咨询',
    desc: '广告主投放的咨询组件确认发生咨询的对话'
  },
  {
    code: 'potentialCustomerOnline',
    name: '潜在客户线索-咨询',
    desc: '广告主投放的咨询组件确认发生留咨的行为'
  },
  { code: 'phoneDialing', name: '电话直拨', desc: '用户点击拨打电话按钮' },
  { code: 'effectiveLeadsPhone', name: '有效线索-电话', desc: '广告主投放的电话组件确认接通' },
  {
    code: 'potentialCustomerPhone',
    name: '潜在客户线索-电话',
    desc: '广告主投放的电话组件接通后确认为潜在客户'
  },
  { code: 'followScan', name: '扫码关注', desc: '跳转到落地页后，产生的扫码关注次数' },
  { code: 'leadsLottery', name: '抽奖线索', desc: '在抽奖后，提交手机号并成功上报' },
  { code: 'addPaymentInfo', name: '添加付款信息', desc: '用于追踪付款信息配置状态' },
  { code: 'startTrial', name: '开始试用', desc: '用于追踪产品的免费试用的开始' },
  { code: 'initiatedCheckout', name: '发起结账', desc: '用于追踪结账事件' },
  { code: 'invite', name: '邀请', desc: '用户产生邀请（社交）行为' },
  { code: 'search', name: '搜索', desc: '用户产生搜索行为' },
  { code: 'share', name: '分享', desc: '用户产生分享行为' },
  { code: 'travelBooking', name: '旅行预订', desc: '用于追踪旅行预订事件（及相关收入）' },
  { code: 'rate', name: '评级', desc: '用于追踪商品/应用评级事件' },
  { code: 'contentView', name: '内容视图', desc: '用于追踪内容视图事件' },
  { code: 'custom', name: '自定义（应用）', desc: '用于追踪自定义转化事件' },
  { code: 'custom_landingpage', name: '自定义（网页）', desc: '用于追踪落地页内自定义转化事件' },
  { code: 'landingpageClick', name: '落地页内按钮点击', desc: '用户点击按钮button' },
  { code: 'coupon', name: '卡券领取', desc: '用户点击卡券领取按钮' },
  { code: 'navigate', name: '门店导航', desc: '用户点击导航按钮' },
  { code: 'lottery', name: '抽奖', desc: '用户点击抽奖按钮' },
  { code: 'vote', name: '投票', desc: '用户点击投票按钮' },
  { code: 'redirect', name: '页面跳转', desc: '用户跳转至其他页面' },
  { code: 'gamePackageRedemption', name: '礼包兑换', desc: '用户兑换礼包' },
  { code: 'gamePackageClaiming', name: '礼包领取', desc: '用户领取礼包' },
  { code: 'createRole', name: '游戏内创建角色', desc: '创建角色' },
  { code: 'authorize', name: '游戏授权', desc: '授权（游戏）' },
  { code: 'tutorialCompletion', name: '游戏完成新手教程', desc: '完成新手教程（游戏）' },
  { code: 'achievementUnlocked', name: '解锁成就', desc: '追踪用户成就解锁的事件' },
  { code: 'spentCredits', name: '花掉积分', desc: '用于追踪用户积分花费的事件' },
  { code: 'levelAchieved', name: '达到级别', desc: '用户达到游戏等级事件' },
  { code: 'loanCompletion', name: '完件', desc: '用户进行相关服务完件' },
  { code: 'preCredit', name: '预授信', desc: '预授信次数' },
  { code: 'credit', name: '授信', desc: '授信次数' },
  { code: 'follow', name: '关注', desc: '被用户关注' },
  { code: 'forward', name: '转发', desc: '被用户转发' },
  { code: 'read', name: '阅读', desc: '被用户阅读' },
  { code: 'like', name: '点赞', desc: '被用户点赞' },
  { code: 'comment', name: '评论', desc: '被用户评论' },
  { code: 'refund', name: '退款', desc: '被用户退款' },
  {
    code: 'qualityActivate',
    name: '优质激活',
    desc: '广告主在普通激活用户中筛选出LTV较高用户定义为优质激活用户'
  }
]
