export default [
  // { code: '1', name: '激活' },
  { code: '2', name: '注册' },
  { code: '3', name: '付费' },
  { code: '5', name: '活跃' },
  { code: '6', name: '优质用户' },
  { code: '10', name: '完件' },
  { code: '11', name: '授信' },
  { code: '12', name: '商品浏览' },
  { code: '13', name: '添加购物车' },
  { code: '14', name: '提交订单' },
  { code: '15', name: '付款成功' },
  { code: '39', name: '人脸识别完成' },
  { code: '40', name: '身份信息填写完成' },
  { code: '41', name: '银行卡信息填写完成' },
  { code: '42', name: '补充个人信息填写完成' },
  { code: '43', name: '首次试听课到客' },
  { code: '44', name: '有效线索' },
  { code: '48', name: '立即购买' },
  { code: '51', name: '支付页曝光' },
  { code: '64', name: '微信复制' },
  { code: '66', name: '确认收货' },
  { code: '69', name: '教育正价课付费' },
  { code: '75', name: '用信' },
  { code: '84', name: '唤起应用' },
  { code: '85', name: '观看广告' },
  // { code: '7', name: '次日留存' },
  // { code: '102', name: '2日留存' },
  // { code: '103', name: '3日留存' },
  // { code: '104', name: '4日留存' },
  // { code: '105', name: '5日留存' },
  // { code: '106', name: '6日留存' },
  // { code: '8', name: '7日留存' },
  // { code: '107', name: '14日留存' },
  // { code: '108', name: '30日留存' },
  { code: '109', name: '电话卡激活' },
  { code: '116', name: '电话建联成功' },
  { code: '117', name: '意向确认' },
  { code: '118', name: '微信加粉' },
  { code: '119', name: '成交' },
  { code: '120', name: '电话建联失败' },
  { code: '121', name: '用户无意向' },
  { code: '139', name: '首次试听课完课' },
  { code: '140', name: '第2次试听课到客' },
  { code: '141', name: '全部试听完课' },
  { code: '143', name: '关键行为' },
  { code: '144', name: '通过游戏关卡' },
  { code: '145', name: '提现' },
  { code: '150', name: '阅读小说章节' },
  { code: '151', name: '大小R付费' },
  { code: '152', name: '乘客首次发单' },
  { code: '153', name: '乘客首次完单' },
  { code: '154', name: '车主提交认证' },
  { code: '155', name: '车主认证通过' },
  { code: '156', name: '车主首次完单' },
  { code: '157', name: '外部预估值回传' }
]
