export default {
  show: '展示',
  // totalShow: '累计展示',
  click: '点击',
  clickUv: '接收到的点击',
  // totalClick: '累计点击',
  ctr: 'CTR',
  ecpm: 'eCPM',
  downloadStart: '下载开始',
  downloadFinish: '下载完成',
  installFinish: '安装完成',
  installFinishRate: '安装完成率',
  active: '激活',
  umengActive: '友盟Callback',
  cvr: 'CVR',
  car: 'CAR',
  avr: 'AVR',
  cost: '成本',
  unitPrice: '激活单价',
  externalAction: '转化目标',
  deepExternalAction: '深度转化目标',
  data_convert: '转化',
  attributionDeepConvert: '深度转化',
  bid: '出价',
  deepCpabid: '深度转化出价',
  deepConvertCost: '深度转化单价',
  deepConvertRate: '深度转化率',
  convert_cost: '转化单价',
  attributionDeepConvertCost: '深度转化单价',
  register: '注册',
  activeRegisterCost: '注册单价',
  payCount: '付费',
  activePayCost: '付费单价',
  attributionNextDayOpenCnt: '次留',
  attributionNextDayOpenCntRate: '次留率',
  // estimateRoi: 'ROI',
  todayRoa: '投放比'
}
