export default {
  indicator: {
    ldrLdStartPv: 'SID触发拉取',
    ldrLdStartUv: 'SID触发拉取UV',
    ldStartPv: '拉取',
    ldStartUv: '拉取UV',
    ldPvRatio: '拉取率',
    ldUvRatio: '拉取率(UV)',
    ldSucceedPv: '填充',
    ldSucceedUv: '填充(UV)',
    fillPvRatio: '填充率',
    fillUvRatio: '填充率(UV)',
    ldrShStartPv: 'SID请求展示',
    ldrShStartUv: 'SID请求展示(UV)',
    shSucceedPv: '展示',
    shSucceedUv: '展示(UV)',
    fillPvUseRatio: '填充展示率',
    fillUvUseRatio: '填充展示率(UV)',
    showPvRatio: 'SID请求展示率',
    showUvRatio: 'SID请求展示率(UV)',
    onclickPv: '点击',
    onclickUv: '点击(UV)',
    pvCtr: '点击率',
    uvCtr: '点击率(UV)',
    realCtr: '平台点击率',
    revenue: '收入',
    realEcpm: 'SID实际展示eCPM',
    cpm: '平台eCPM',
    requestShowEcpm: 'SID请求展示eCPM',
    realCpc: 'CPC',
    cpc: '平台CPC',
    avgPull: '人均拉取',
    avgShow: '人均展示',
    avgClick: '人均点击'
  }
}
