const FIELD_TYPE_LINK_INPUT = 'link_input'
const FIELD_TYPE_LINK_INPUT_LABEL = '链接输入框'

const FIELD_TYPE_NUMBER_INPUT = 'number_input'
const FIELD_TYPE_NUMBER_INPUT_LABEL = '整数输入框'

const FIELD_TYPE_NORMAL_INPUT = 'normal_input'
const FIELD_TYPE_NORMAL_INPUT_LABEL = '普通输入框'

const FIELD_TYPE_MULTIPLE_SELECT = 'multiple_select'
const FIELD_TYPE_MULTIPLE_SELECT_LABEL = '多选'

const FIELD_TYPE_SINGLE_SELECT = 'single_select'
const FIELD_TYPE_SINGLE_SELECT_LABEL = '单选'

const FIELD_TYPE_SWITCH = 'switch_control'
const FIELD_TYPE_SWITCH_LABEL = '开关'

const FIELD_TYPE_ASK = 'field_type_ask'
const FIELD_TYPE_ASK_LABEL = 'AK and SK'

const doField = {
  FIELD_TYPE_LINK_INPUT,
  FIELD_TYPE_NUMBER_INPUT,
  FIELD_TYPE_NORMAL_INPUT,
  FIELD_TYPE_MULTIPLE_SELECT,
  FIELD_TYPE_SINGLE_SELECT,
  FIELD_TYPE_SWITCH,
  FIELD_TYPE_ASK,
  labelMap: {
    [FIELD_TYPE_LINK_INPUT]: FIELD_TYPE_LINK_INPUT_LABEL,
    [FIELD_TYPE_NUMBER_INPUT]: FIELD_TYPE_NUMBER_INPUT_LABEL,
    [FIELD_TYPE_NORMAL_INPUT]: FIELD_TYPE_NORMAL_INPUT_LABEL,
    [FIELD_TYPE_MULTIPLE_SELECT]: FIELD_TYPE_MULTIPLE_SELECT_LABEL,
    [FIELD_TYPE_SINGLE_SELECT]: FIELD_TYPE_SINGLE_SELECT_LABEL,
    [FIELD_TYPE_SWITCH]: FIELD_TYPE_SWITCH_LABEL,
    [FIELD_TYPE_ASK]: FIELD_TYPE_ASK_LABEL
  },
  options: [
    FIELD_TYPE_LINK_INPUT,
    FIELD_TYPE_NUMBER_INPUT,
    FIELD_TYPE_NORMAL_INPUT,
    FIELD_TYPE_MULTIPLE_SELECT,
    FIELD_TYPE_SINGLE_SELECT,
    FIELD_TYPE_SWITCH,
    FIELD_TYPE_ASK
  ]
}
export default doField
